Hii In this file we will learn pandas 

### Pandas is a library that helps you handle tabular data
- Data in Pandas is stored as dataframes, a 2-d structure similar to the tables in excel
- Pandas offers transformations, data cleaning, preprocessing options, and hence pandas library becomes an eminent part of life of DE and DS
- Pandas offers two data abstraction models - Series and DataFrame

In [ ]:
#Series in pandas is a 1-d data. Dataframe is a 2-d data. Other than that we do not have any dimensional data in pandas

In [3]:
import pandas as pd
#A series can be constructed from a list, tuple, a np.1-d array, a dictionary. But a series cannot be constructed from a set.
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
ser1 = pd.Series([3,4,5,6], index = ['row1','row2','row3','row4'], name = "Series1")
ser1

row1    3
row2    4
row3    5
row4    6
Name: Series1, dtype: int64

In [9]:
df = pd.DataFrame([[1,2,3,4,5],[5,6,7]])
df

   0  1  2    3    4
0  1  2  3  4.0  5.0
1  5  6  7  NaN  NaN

In [ ]:
df2=pd.DataFrame(ser1)
df2

In [10]:
df = pd.DataFrame([[1,2,3],[6,7,8],[9,4,3,2,6,8]], index=['row1','row2','row3'], columns = ['col1','col2','col3','col4','col5','col6'])
df

      col1  col2  col3  col4  col5  col6
row1     1     2     3   NaN   NaN   NaN
row2     6     7     8   NaN   NaN   NaN
row3     9     4     3   2.0   6.0   8.0

In [ ]:
df.rename(columns = {'col1':'c1'}, inplace=True)   #inplace=True ensures that a permanent change is done in the variablef

In [11]:
df

      col1  col2  col3  col4  col5  col6
row1     1     2     3   NaN   NaN   NaN
row2     6     7     8   NaN   NaN   NaN
row3     9     4     3   2.0   6.0   8.0

In [12]:
df.isnull()

       col1   col2   col3   col4   col5   col6
row1  False  False  False   True   True   True
row2  False  False  False   True   True   True
row3  False  False  False  False  False  False

In [15]:
data = pd.read_csv('titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

In [17]:
data.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [18]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [19]:
data.describe(include='O')

                           Name   Sex  Ticket Cabin Embarked
count                       156   156     156    31      155
unique                      156     2     145    28        3
top     Braund, Mr. Owen Harris  male  113803  C123        S
freq                          1   100       2     2      110

In [20]:
data.shape

(156, 12)

In [21]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [23]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [24]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [27]:
data.Sex.unique()

array(['male', 'female'], dtype=object)

In [29]:
data.Sex.value_counts()

Sex
male      100
female     56
Name: count, dtype: int64

In [32]:
data.Sex[3]
data['Sex'][4]

'male'